#!/usr/bin/env python3
"""
Auto-generate aegis.h by including all .h headers located in include/aegis/.
Works on Linux, macOS, and Windows.
"""

from pathlib import Path

def main():
    script_dir = Path(__file__).resolve().parent      # <project>/include/
    aegis_dir = script_dir / "aegis"                  # <project>/include/aegis/
    output_file = script_dir / "aegis.h"              # <project>/include/aegis.h

    if not aegis_dir.exists():
        print(f"Error: directory not found: {aegis_dir}")
        return

    # Get all .h files from include/aegis/
    headers = sorted([p.name for p in aegis_dir.glob("*.h")])

    if not headers:
        print(f"No .h files found in {aegis_dir}")
        return

    print("Generating:", output_file)

    with output_file.open("w", encoding="utf-8") as out:
        out.write("/* Auto-generated by create_aegis_h.py */\n")
        out.write("#ifndef AEGIS_H\n")
        out.write("#define AEGIS_H\n\n")

        # Use POSIX-style include paths even on Windows (<aegis/file.h>)
        for header in headers:
            out.write(f"#include \"aegis/{header}\"\n")

        out.write("\n#endif /* AEGIS_H */\n")

    print("Done!")

if __name__ == "__main__":
    main()

